version: '3.8'

services:
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}_accounts
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=app
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27128:27017
    volumes:
      - .mongodb:/data/db
    networks:
      - default

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}_network
